### ISSUE TITLE
Unable to load factory

### ISSUE THREAD

**Issue by kielabokkie** [JoggApp/laravel-mail-viewer#4] opened 2018-09-25 02:44 UTC
I'm trying to use this on a L5.7 project but whenever I try to pass factories as parameters for my mailable I get the following error:

```
Unable to locate factory with name [default] [App\User].
```

Below a snippet from my config file:
```
'mailables' => [
    new SignedUp(factory(\App\User::class)->create(), factory(\App\User::class)->create())
],
```

I have a User class with the namespace `\App\User` and a `database/factories/UserFactory.php` with a default definition. Any idea what is causing this error?

**Comment by introwit** [comment] 2018-09-25 14:40
@kielabokkie you are right, looking into it. Will get back to you as soon as the issue is solved :)

**Comment by introwit** [comment] 2018-09-27 03:02
@kielabokkie fixed in the new [v2.0.0](https://github.com/JoggApp/laravel-mail-viewer/releases/tag/v2.0.0) release :) Also there are changes in how the mailables are to be registered in the config file, so please have a look at the [new config file](https://github.com/JoggApp/laravel-mail-viewer/blob/master/config/mailviewer.php#L4-L32) and make the changes accordingly :) Lemme know how it goes 😄

**Closed by introwit** 2018-09-27 03:02 UTC
Labels: bug

**Comment by kielabokkie** [comment] 2018-09-27 21:05
Thanks @introwit, new version fixes the problem 👍

I'm having some trouble getting the middleware to work so only authenticated users can access it but that could be specific middleware config at my end so I'll see if I can replicate that on a clean install.

**Comment by introwit** [comment] 2018-09-27 21:07
@kielabokkie sure, feel free to open a new issue if the problem persists 😄
